// Real photos shown on the fact cards. Every photo is free to share; see CREDITS.md.
export const PHOTOS = {
  plankton: { file: "art/animals/plankton.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Zooplankton.jpg" },
  sardine: { file: "art/animals/sardine.webp", credit: "Photo: Roberto Pillon, CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Sardina_pilchardus_Sardinia.JPG" },
  mackerel: { file: "art/animals/mackerel.webp", credit: "Photo: Brian Gratwicke, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Scomber_japonicus_Mackrel!_(5625008836).jpg" },
  squid: { file: "art/animals/squid.webp", credit: "Photo: Nick Hobgood, CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Sepioteuthis_sepioidea_(Caribbean_Reef_Squid).jpg" },
  tuna: { file: "art/animals/tuna.webp", credit: "Photo: aes256, CC BY 2.1 JP", source: "https://commons.wikimedia.org/wiki/File:Pacific_bluefin_tuna.jpg" },
  shark: { file: "art/animals/shark.webp", credit: "Photo: Terry Goss, CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:White_shark.jpg" },
  seahorse: { file: "art/animals/seahorse.webp", credit: "Photo: Hans Hillewaert, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Hippocampus_hippocampus_(on_Ascophyllum_nodosum).jpg" },
  turtle: { file: "art/animals/turtle.webp", credit: "Photo: Brocken Inaglory, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Total_internal_reflection_of_Chelonia_mydas.jpg" },
  octopus: { file: "art/animals/octopus.webp", credit: "Photo: H. Zell, CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Octopus_vulgaris_03.jpg" },
  starfish: { file: "art/animals/starfish.webp", credit: "Photo: Ed Bierman, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Pisaster_ochraceus_(2806825367).jpg" },
  crab: { file: "art/animals/crab.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Grapsus_grapsus_Galapagos_Islands.jpg" },
  parrotfish: { file: "art/animals/parrotfish.webp", credit: "Photo: Diego Delso, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pez_loro_tricolor_(Scarus_tricolor),_Nosy_Iranja,_Madagascar,_2025-09-17,_DD_61.jpg" },
  clownfish: { file: "art/animals/clownfish.webp", credit: "Photo: Janderk, public domain", source: "https://commons.wikimedia.org/wiki/File:Common_clownfish.jpg" },
  orca: { file: "art/animals/orca.webp", credit: "Photo: Robert Pittman (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Killerwhales_jumping.jpg" },
  dolphin: { file: "art/animals/dolphin.webp", credit: "Photo: NASA, public domain", source: "https://commons.wikimedia.org/wiki/File:Tursiops_truncatus_01.jpg" },
  jellyfish: { file: "art/animals/jellyfish.webp", credit: "Photo: Ed Bierman, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Sea_nettle_(Chrysaora_fuscescens)_2.jpg" },
  pufferfish: { file: "art/animals/pufferfish.webp", credit: "Photo: Richard Ling, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Arothron_nigropunctatus.jpg" },
  bluewhale: { file: "art/animals/bluewhale.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg" },
  manta: { file: "art/animals/manta.webp", credit: "Photo: Rickard Zerpe, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Reef_manta_ray_(Manta_alfredi)_-_49877611423.jpg" },
  lobster: { file: "art/animals/lobster.webp", credit: "Photo: Bart Braun, public domain", source: "https://commons.wikimedia.org/wiki/File:KreeftbijDenOsse.jpg" },
  urchin: { file: "art/animals/urchin.webp", credit: "Photo: Dwayne Meadows (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Fish4641_-_Flickr_-_NOAA_Photo_Library.jpg" },
  hammerhead: { file: "art/animals/hammerhead.webp", credit: "Photo: Marko Dimitrijevic, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Hammerhead_Shark_-_Marko_Dimitrijevic.jpg" },
  whaleshark: { file: "art/animals/whaleshark.webp", credit: "Photo: FGBNMS/Eckert (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Rhincodon_typus_fgbnms.jpg" },
  narwhal: { file: "art/animals/narwhal.webp", credit: "Photo: Kristin Laidre (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Pod_Monodon_monoceros.jpg" },
  anglerfish: { file: "art/animals/anglerfish.webp", credit: "Photo: NOAA Okeanos Explorer, public domain", source: "https://commons.wikimedia.org/wiki/File:Lophiodes-hires.jpg" },
  otter: { file: "art/animals/otter.webp", credit: "Photo: Marshal Hedin, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Sea_Otter_(Enhydra_lutris)_(25169790524).jpg" },
  penguin: { file: "art/animals/penguin.webp", credit: "Photo: Ken Funakoshi, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Pygoscelis_papua_-Nagasaki_Penguin_Aquarium_-swimming_underwater-8a.jpg" },
  flyingfish: { file: "art/animals/flyingfish.webp", credit: "Photo: Ronald van der Graaf, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Vliegende_vis_(Exocoetidae).jpg" },
  manofwar: { file: "art/animals/manofwar.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Portuguese_Man-O-War_(Physalia_physalis).jpg" },
  mantisshrimp: { file: "art/animals/mantisshrimp.webp", credit: "Photo: Cédric Péneau, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Odontodactylus_scyllarus_R%C3%A9union.jpg" },
  seacucumber: { file: "art/animals/seacucumber.webp", credit: "Photo: Bernard Dupont, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Sea_Cucumber_(Thelenota_ananas)_(6094180400).jpg" },
  moray: { file: "art/animals/moray.webp", credit: "Photo: Greg McFall (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:FKNMS_Green_Moray_Eel_(48779495451).jpg" },
  horseshoecrab: { file: "art/animals/horseshoecrab.webp", credit: "Photo: Hans Hillewaert, CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Limulus_polyphemus_(aquarium).jpg" },
  // Coral reef
  damselfish: { file: "art/animals/damselfish.webp", credit: "Photo: Brian Gratwicke, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Blue_Damselfish_Chrysiptera_cyanea.jpg" },
  lionfish: { file: "art/animals/lionfish.webp", credit: "Photo: Jens Petersen, CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:Pterois_volitans_Manado-e_edit.jpg" },
  grouper: { file: "art/animals/grouper.webp", credit: "Photo: q phia, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:2017,_cuba,_jardines_aggressor,_los_indios,_nassau_grouper_maw_(36883128693).jpg" },
  reefshark: { file: "art/animals/reefshark.webp", credit: "Photo: Charles J. Sharp, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Blacktip_reef_shark_(Carcharhinus_melanopterus)_Moorea_3.jpg" },
  tigershark: { file: "art/animals/tigershark.webp", credit: "Photo: Albert kok, CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Tiger_shark.jpg" },
  coral: { file: "art/animals/coral.webp", credit: "Photo: Diego Delso, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Coral_(Galaxea_fascicularis),_mar_Rojo,_Egipto,_2023-04-18,_DD_128.jpg" },
  giantclam: { file: "art/animals/giantclam.webp", credit: "Photo: Diego Delso, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Almeja_gigante_(Tridacna_maxima),_mar_Rojo,_Egipto,_2023-04-18,_DD_103.jpg" },
  // The deep. No free photo of a live vampire squid exists, so its card shows a 1911 scientific drawing.
  marinesnow: { file: "art/animals/marinesnow.webp", credit: "Photo: NOAA National Ocean Service, public domain", source: "https://commons.wikimedia.org/wiki/File:Marinesnow-splash.jpg" },
  deepshrimp: { file: "art/animals/deepshrimp.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Acanthephyra.jpg" },
  lanternfish: { file: "art/animals/lanternfish.webp", credit: "Photo: NOAA/OER, public domain", source: "https://commons.wikimedia.org/wiki/File:Lanternfish_by_NOAA.jpg" },
  viperfish: { file: "art/animals/viperfish.webp", credit: "Photo: NOAA Okeanos Explorer, public domain", source: "https://commons.wikimedia.org/wiki/File:Chauliodus_(Samoa).jpg" },
  giantsquid: { file: "art/animals/giantsquid.webp", credit: "Photo: Tim Evanson, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Architeuthis_dux_-_Smithsonain_Museum.JPG" },
  spermwhale: { file: "art/animals/spermwhale.webp", credit: "Photo: Gabriel Barathieu, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Mother_and_baby_sperm_whale.jpg" },
  hatchetfish: { file: "art/animals/hatchetfish.webp", credit: "Photo: Jan Ebr & Ivana Ebrová, CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Argyropelecus_aculeatus_544343917.jpg" },
  barreleye: { file: "art/animals/barreleye.webp", credit: "Photo: NOAA Ocean Exploration, public domain", source: "https://commons.wikimedia.org/wiki/File:Barreleye-fish_GoK.jpg" },
  vampiresquid: { file: "art/animals/vampiresquid.webp", credit: "Drawing: Carl Chun, 1911, public domain", source: "https://commons.wikimedia.org/wiki/File:Vampyroteuthis_infernalis.jpg" },
  combjelly: { file: "art/animals/combjelly.webp", credit: "Photo: Chad King (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Lobate_Comb_Jelly_(40164874905).jpg" },
  oarfish: { file: "art/animals/oarfish.webp", credit: "Photo: Ryokou man, public domain", source: "https://commons.wikimedia.org/wiki/File:20100216_acaworld07.jpg" },
};
