// Real photos shown on the fact cards. Every photo is free to share; see CREDITS.md.
export const PHOTOS = {
  plankton: { file: "art/animals/plankton.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Zooplankton.jpg" },
  sardine: { file: "art/animals/sardine.webp", credit: "Photo: Roberto Pillon, CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Sardina_pilchardus_Sardinia.JPG" },
  mackerel: { file: "art/animals/mackerel.webp", credit: "Photo: Brian Gratwicke, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Scomber_japonicus_Mackrel!_(5625008836).jpg" },
  squid: { file: "art/animals/squid.webp", credit: "Photo: Nick Hobgood, CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Sepioteuthis_sepioidea_(Caribbean_Reef_Squid).jpg" },
  tuna: { file: "art/animals/tuna.webp", credit: "Photo: aes256, CC BY 2.1 JP", source: "https://commons.wikimedia.org/wiki/File:Pacific_bluefin_tuna.jpg" },
  shark: { file: "art/animals/shark.webp", credit: "Photo: Terry Goss, CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:White_shark.jpg" },
  seahorse: { file: "art/animals/seahorse.webp", credit: "Photo: Hans Hillewaert, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Hippocampus_hippocampus_(on_Ascophyllum_nodosum).jpg" },
  turtle: { file: "art/animals/turtle.webp", credit: "Photo: Brocken Inaglory, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Total_internal_reflection_of_Chelonia_mydas.jpg" },
  octopus: { file: "art/animals/octopus.webp", credit: "Photo: H. Zell, CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Octopus_vulgaris_03.jpg" },
  starfish: { file: "art/animals/starfish.webp", credit: "Photo: Ed Bierman, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Pisaster_ochraceus_(2806825367).jpg" },
  crab: { file: "art/animals/crab.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Grapsus_grapsus_Galapagos_Islands.jpg" },
  parrotfish: { file: "art/animals/parrotfish.webp", credit: "Photo: Diego Delso, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pez_loro_tricolor_(Scarus_tricolor),_Nosy_Iranja,_Madagascar,_2025-09-17,_DD_61.jpg" },
  clownfish: { file: "art/animals/clownfish.webp", credit: "Photo: Janderk, public domain", source: "https://commons.wikimedia.org/wiki/File:Common_clownfish.jpg" },
  orca: { file: "art/animals/orca.webp", credit: "Photo: Robert Pittman (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Killerwhales_jumping.jpg" },
  dolphin: { file: "art/animals/dolphin.webp", credit: "Photo: NASA, public domain", source: "https://commons.wikimedia.org/wiki/File:Tursiops_truncatus_01.jpg" },
  jellyfish: { file: "art/animals/jellyfish.webp", credit: "Photo: Ed Bierman, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Sea_nettle_(Chrysaora_fuscescens)_2.jpg" },
  pufferfish: { file: "art/animals/pufferfish.webp", credit: "Photo: Richard Ling, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Arothron_nigropunctatus.jpg" },
  bluewhale: { file: "art/animals/bluewhale.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg" },
  manta: { file: "art/animals/manta.webp", credit: "Photo: Rickard Zerpe, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Reef_manta_ray_(Manta_alfredi)_-_49877611423.jpg" },
  lobster: { file: "art/animals/lobster.webp", credit: "Photo: Bart Braun, public domain", source: "https://commons.wikimedia.org/wiki/File:KreeftbijDenOsse.jpg" },
  urchin: { file: "art/animals/urchin.webp", credit: "Photo: Dwayne Meadows (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Fish4641_-_Flickr_-_NOAA_Photo_Library.jpg" },
  hammerhead: { file: "art/animals/hammerhead.webp", credit: "Photo: Marko Dimitrijevic, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Hammerhead_Shark_-_Marko_Dimitrijevic.jpg" },
  whaleshark: { file: "art/animals/whaleshark.webp", credit: "Photo: FGBNMS/Eckert (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Rhincodon_typus_fgbnms.jpg" },
  narwhal: { file: "art/animals/narwhal.webp", credit: "Photo: Kristin Laidre (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:Pod_Monodon_monoceros.jpg" },
  anglerfish: { file: "art/animals/anglerfish.webp", credit: "Photo: NOAA Okeanos Explorer, public domain", source: "https://commons.wikimedia.org/wiki/File:Lophiodes-hires.jpg" },
  otter: { file: "art/animals/otter.webp", credit: "Photo: Marshal Hedin, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Sea_Otter_(Enhydra_lutris)_(25169790524).jpg" },
  penguin: { file: "art/animals/penguin.webp", credit: "Photo: Ken Funakoshi, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Pygoscelis_papua_-Nagasaki_Penguin_Aquarium_-swimming_underwater-8a.jpg" },
  flyingfish: { file: "art/animals/flyingfish.webp", credit: "Photo: Ronald van der Graaf, CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Vliegende_vis_(Exocoetidae).jpg" },
  manofwar: { file: "art/animals/manofwar.webp", credit: "Photo: NOAA, public domain", source: "https://commons.wikimedia.org/wiki/File:Portuguese_Man-O-War_(Physalia_physalis).jpg" },
  mantisshrimp: { file: "art/animals/mantisshrimp.webp", credit: "Photo: Cédric Péneau, CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Odontodactylus_scyllarus_R%C3%A9union.jpg" },
  seacucumber: { file: "art/animals/seacucumber.webp", credit: "Photo: Bernard Dupont, CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Sea_Cucumber_(Thelenota_ananas)_(6094180400).jpg" },
  moray: { file: "art/animals/moray.webp", credit: "Photo: Greg McFall (NOAA), public domain", source: "https://commons.wikimedia.org/wiki/File:FKNMS_Green_Moray_Eel_(48779495451).jpg" },
  horseshoecrab: { file: "art/animals/horseshoecrab.webp", credit: "Photo: Hans Hillewaert, CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Limulus_polyphemus_(aquarium).jpg" },
};
